export const allClients = [
    {
        slug: '1',
        contact: 'Wade Warren',
        company: 'Astra Payroll Services',
        status: 'Pending',
        program_start_date: '2023-01-12',
        total_mca_debt: 1531,
        last_interaction: '2024-01-12',
    },
    {
        slug: '2',
        contact: 'Leslie Alexander',
        company: 'PayNortheast',
        status: 'Completed',
        program_start_date: '2023-01-15',
        total_mca_debt: 3421,
        last_interaction: '2024-01-15',
    },
    {
        slug: '3',
        contact: 'Guy Hawkins',
        company: 'Netpay Payroll',
        status: 'On Hold',
        program_start_date: '2023-01-25',
        total_mca_debt: 499,
        last_interaction: '2024-01-25',
    },
    {
        slug: '4',
        contact: 'Jerome Bell',
        company: 'CPRI',
        status: 'On Hold',
        program_start_date: '2023-02-12',
        total_mca_debt: 536,
        last_interaction: '2024-02-12',
    },
    {
        slug: '5',
        contact: 'Wade Warren',
        company: 'Commonwealth Payroll',
        status: 'Completed',
        program_start_date: '2023-02-15',
        total_mca_debt: 1072,
        last_interaction: '2024-02-15',
    },
    {
        slug: '6',
        contact: 'Leslie Alexander',
        company: 'APS Payroll Services',
        status: 'On Hold',
        program_start_date: '2023-02-25',
        total_mca_debt: 977,
        last_interaction: '2024-02-25',
    },
    {
        slug: '7',
        contact: 'Guy Hawkins',
        company: 'Businessworld',
        status: 'In Progress',
        program_start_date: '2023-03-12',
        total_mca_debt: 617,
        last_interaction: '2024-03-12',
    },
    {
        slug: '8',
        contact: 'Jerome Bell',
        company: 'HR Ally',
        status: 'Pending',
        program_start_date: '2023-03-15',
        total_mca_debt: 714,
        last_interaction: '2024-03-15',
    },
    {
        slug: '9',
        contact: 'Wade Warren',
        company: 'Pharos Payroll',
        status: 'In Progress',
        program_start_date: '2023-03-25',
        total_mca_debt: 158,
        last_interaction: '2024-03-25',
    },
    {
        slug: '10',
        contact: 'Jerome Bell',
        company: 'CustomPay',
        status: 'In Progress',
        program_start_date: '2023-04-12',
        total_mca_debt: 516,
        last_interaction: '2024-04-12',
    },
];
