// Dummy data for the new fields
export const clientRevenuData = [
    {
        slug: '1',
        clientCompanyName: 'Company X',
        revenueSourceType: 'A',
        revenueSourceCompanyName: 'Company Y',
        contactName: 'Alice Johnson',
        contactPhone: '555-555-5555',
        contactEmail: 'alice@example.com',
        oldCoId: 'Old123',
        newCoId: 'New123',
        oldCoLogin: 'old_user',
        newCoLogin: 'new_user',
        notes: 'Initial setup',
    },
    {
        slug: '2',
        clientCompanyName: 'Company Z',
        revenueSourceType: 'B',
        revenueSourceCompanyName: 'Company W',
        contactName: 'Bob Smith',
        contactPhone: '555-666-7777',
        contactEmail: 'bob@example.com',
        oldCoId: 'Old456',
        newCoId: 'New456',
        oldCoLogin: 'old_admin',
        newCoLogin: 'new_admin',
        notes: 'Migration completed',
    },
    {
        slug: '3',
        clientCompanyName: 'Company Y',
        revenueSourceType: 'C',
        revenueSourceCompanyName: 'Company W',
        contactName: 'Bob Smith',
        contactPhone: '555-666-7777',
        contactEmail: 'bob@example.com',
        oldCoId: 'Old456',
        newCoId: 'New456',
        oldCoLogin: 'old_admin',
        newCoLogin: 'new_admin',
        notes: 'Migration completed',
    },
];
