export const clientAdData = [
    {
        slug: '1',
        client_company_name: 'Tech Innovators Inc',
        ad_company_name: 'AdMaster',
        name: 'Alice Johnson',
        phone: '555-1234',
        email: 'alice.johnson@admaster.com',
        status: 'Active',
        notes: 'Ongoing campaign for new product launch.',
    },
    {
        slug: '2',
        client_company_name: 'Green Solutions Ltd',
        ad_company_name: 'PromoWave',
        name: 'Bob Smith',
        phone: '555-5678',
        email: 'bob.smith@promowave.com',
        status: 'Pending',
        notes: 'Proposal submitted, awaiting feedback.',
    },
    {
        slug: '3',
        client_company_name: 'Global Enterprises',
        ad_company_name: 'AdPro',
        name: 'Charlie Brown',
        phone: '555-8765',
        email: 'charlie.brown@adpro.com',
        status: 'Completed',
        notes: 'Campaign concluded with positive results.',
    },
    {
        slug: '4',
        client_company_name: 'NextGen Tech',
        ad_company_name: 'AdStar',
        name: 'Diana Miller',
        phone: '555-4321',
        email: 'diana.miller@adstar.com',
        status: 'In Progress',
        notes: 'Current campaign in the optimization phase.',
    },
    {
        slug: '5',
        client_company_name: 'Eco Friendly Products',
        ad_company_name: 'AdWorks',
        name: 'Evan Davis',
        phone: '555-3456',
        email: 'evan.davis@adworks.com',
        status: 'Cancelled',
        notes: 'Campaign cancelled due to budget constraints.',
    },
];
