export const localCounselDetailsData = [
    {
        slug: '1',
        amount: '2000',
        status: 'Pending',
        clientCompanyName: 'Robert Wilson',
        localCounselName:'CL1',
        localCounselJurisdiction: 'California, Nevada',
        name: 'Robert Wilson',
        phone: '555-1234',
        email: 'robert.wilson@lawfirm.com',
        hourlyRate: '$300',
        retainer: '$5000',
        notes: 'Experienced in corporate law and mergers.',
        date: '2-08-2024',
    },
    {
        slug: '2',
        amount: '2000',
        status: 'Pending',
        clientCompanyName: 'Laura Martinez',
        localCounselName:'CL1',
        localCounselJurisdiction: 'New York, New Jersey',
        name: 'Laura Martinez',
        phone: '555-5678',
        email: 'laura.martinez@legalgroup.com',
        hourlyRate: '$250',
        retainer: '$4000',
        date: '2-08-2024',
        notes: 'Specializes in intellectual property and technology law.',
    },
    {
        slug: '3',
        amount: '2000',
        status: 'Completed',
        clientCompanyName: 'Emily Davis',
        localCounselName:'CL1',
        localCounselJurisdiction: 'Texas',
        name: 'Emily Davis',
        phone: '555-8765',
        email: 'emily.davis@davislegal.com',
        hourlyRate: '$275',
        retainer: '$4500',
        date: '2-08-2024',
        notes: 'Focuses on employment law and labor relations.',
    },
    {
        slug: '4',
        amount: '2000',
        status: 'Active',
        clientCompanyName: 'James Anderson',
        localCounselJurisdiction: 'Florida',
        localCounselName:'CL1',
        name: 'James Anderson',
        phone: '555-4321',
        email: 'james.anderson@andersonlaw.com',
        hourlyRate: '$320',
        retainer: '$5500',
        date: '2-08-2024',
        notes: 'Expert in real estate and land use law.',
    },
    {
        slug: '5',
        amount: '2000',
        status: 'Pending',
        clientCompanyName: 'Sarah Brown',
        localCounselName:'CL1',
        localCounselJurisdiction: 'Illinois',
        name: 'Sarah Brown',
        phone: '555-3456',
        email: 'sarah.brown@brownlaw.com',
        hourlyRate: '$290',
        retainer: '$4800',
        date: '2-08-2024',
        notes: 'Skilled in family law and personal injury.',
    },
];
