export const mCA3rdParty = [
    {
        slug: '1',
        thirdPartyCompanyName: 'Alpha Consulting',
        mcaCompanyName: 'MCA Partners',
        thirdPartyType: 'Consultant',
        relationshipType: 'Partner',
        nameOfOtherThirdParty: 'Beta Solutions',
        businessWebsite: 'https://www.alphaconsulting.com',
        businessAddress: '123 Main Street, Suite 400, New York, NY 10001',
        name: 'John Doe',
        phone: '+1-212-555-1234',
        email: 'john.doe@alphaconsulting.com',
        collaborationLevel: 'High',
        notes: 'Long-term partner with strong ties to the industry.',
    },
    {
        slug: '2',
        thirdPartyCompanyName: 'Alpha Consulting',
        mcaCompanyName: 'MCA Partners',
        thirdPartyType: 'Consultant',
        relationshipType: 'Partner',
        nameOfOtherThirdParty: 'Beta Solutions',
        businessWebsite: 'https://www.alphaconsulting.com',
        businessAddress: '123 Main Street, Suite 400, New York, NY 10001',
        name: 'John Doe',
        phone: '+1-212-555-1234',
        email: 'john.doe@alphaconsulting.com',
        collaborationLevel: 'High',
        notes: 'Long-term partner with strong ties to the industry.',
    },
    {
        slug: '3',
        thirdPartyCompanyName: 'Alpha Consulting',
        mcaCompanyName: 'MCA Partners',
        thirdPartyType: 'Consultant',
        relationshipType: 'Partner',
        nameOfOtherThirdParty: 'Beta Solutions',
        businessWebsite: 'https://www.alphaconsulting.com',
        businessAddress: '123 Main Street, Suite 400, New York, NY 10001',
        name: 'John Doe',
        phone: '+1-212-555-1234',
        email: 'john.doe@alphaconsulting.com',
        collaborationLevel: 'High',
        notes: 'Long-term partner with strong ties to the industry.',
    },
];
