export const mcaData = [
    {
        slug: '1',
        mcaCompanyName: 'FastCash Solutions',
        businessWebsite: 'https://www.fastcash.com',
        businessAddress: '123 Finance St, Suite 456, Capital City',
        contactName: 'John Doe',
        contactPhone: '+1 (555) 123-4567',
        contactEmail: 'john.doe@fastcash.com',
        settlementPatterns: 'Weekly payments, high volume',
        collaborationLevel: 'High',
        notes: 'Consistently on time with payments.',
    },
    {
        slug: '2',
        mcaCompanyName: 'QuickFunds Ltd.',
        businessWebsite: 'https://www.quickfunds.com',
        businessAddress: '789 Money Ave, Suite 101, Commerce Town',
        contactName: 'Jane Smith',
        contactPhone: '+1 (555) 234-5678',
        contactEmail: 'jane.smith@quickfunds.com',
        settlementPatterns: 'Bi-weekly payments, medium volume',
        collaborationLevel: 'Medium',
        notes: 'Occasional delays, but overall reliable.',
    },
    {
        slug: '3',
        mcaCompanyName: 'CapitalAdvance Co.',
        businessWebsite: 'https://www.capitaladvance.com',
        businessAddress: '456 Loan Blvd, Floor 3, Finance City',
        contactName: 'Robert Wilson',
        contactPhone: '+1 (555) 345-6789',
        contactEmail: 'robert.wilson@capitaladvance.com',
        settlementPatterns: 'Monthly payments, low volume',
        collaborationLevel: 'Low',
        notes: 'Rarely engages in additional business opportunities.',
    },
    {
        slug: '4',
        mcaCompanyName: 'MoneyMart Group',
        businessWebsite: 'https://www.moneymart.com',
        businessAddress: '321 Cash Rd, Suite 202, Business District',
        contactName: 'Laura Martinez',
        contactPhone: '+1 (555) 456-7890',
        contactEmail: 'laura.martinez@moneymart.com',
        settlementPatterns: 'Weekly payments, high volume',
        collaborationLevel: 'High',
        notes: 'Frequent collaborations on new projects.',
    },
    {
        slug: '5',
        mcaCompanyName: 'AdvanceFunds Inc.',
        businessWebsite: 'https://www.advancefunds.com',
        businessAddress: '654 Credit Ln, Suite 303, Investment Hub',
        contactName: 'James Anderson',
        contactPhone: '+1 (555) 567-8901',
        contactEmail: 'james.anderson@advancefunds.com',
        settlementPatterns: 'Monthly payments, high volume',
        collaborationLevel: 'Medium',
        notes: 'Engages in occasional high-value transactions.',
    },
];
