export const clientLoanData = [
    {
        slug: "1",
        clientMcaLoanName: 'FastCash Solutions - $50,000',
        clientCompanyName: 'Acme Corp',
        mcaCompanyName: 'FastCash Solutions',
        typeOfContract: 'Term Loan',
        originalRtr: '$50,000',
        loanDate: '2024-01-15',
        paymentFrequency: 'Monthly',
        paymentAmount: '$5,000',
        actualPayments: '$5,000',
        actualPaymentNote: 'On-time payment',
        specifiedPercentage: '10%',
        actualPaymentDue: '$5,000',
        overUnderPayment: '$0',
        fbd: 'No',
        currentRtrBalance: '$45,000',
        principalBalance: '$45,000',
        demandBalance: '$50,000',
        paymentStatus: 'Paid',
        lienStatus: 'Cleared',
        settlementPriority: 'High',
        notes: 'No issues reported.',
    },
    {
        slug: "2",
        clientMcaLoanName: 'QuickFunds Ltd. - $30,000',
        clientCompanyName: 'Beta Inc',
        mcaCompanyName: 'QuickFunds Ltd.',
        typeOfContract: 'Revolving Credit',
        originalRtr: '$30,000',
        loanDate: '2024-02-20',
        paymentFrequency: 'Quarterly',
        paymentAmount: '$7,500',
        actualPayments: '$7,500',
        actualPaymentNote: 'Payment received',
        specifiedPercentage: '15%',
        actualPaymentDue: '$7,500',
        overUnderPayment: '$0',
        fbd: 'No',
        currentRtrBalance: '$22,500',
        principalBalance: '$22,500',
        demandBalance: '$30,000',
        paymentStatus: 'Paid',
        lienStatus: 'Active',
        settlementPriority: 'Medium',
        notes: 'Consistent payments.',
    },
    {
        slug: "3",
        clientMcaLoanName: 'CapitalAdvance Co. - $40,000',
        clientCompanyName: 'Gamma Ltd',
        mcaCompanyName: 'CapitalAdvance Co.',
        typeOfContract: 'Line of Credit',
        originalRtr: '$40,000',
        loanDate: '2024-03-10',
        paymentFrequency: 'Monthly',
        paymentAmount: '$4,000',
        actualPayments: '$4,500',
        actualPaymentNote: 'Overpayment recorded',
        specifiedPercentage: '12%',
        actualPaymentDue: '$4,800',
        overUnderPayment: '-$300',
        fbd: 'Yes',
        currentRtrBalance: '$35,000',
        principalBalance: '$35,000',
        demandBalance: '$40,000',
        paymentStatus: 'Paid',
        lienStatus: 'Active',
        settlementPriority: 'High',
        notes: 'Extra payment applied to principal.',
    },
    {
        slug: "4",
        clientMcaLoanName: 'MoneyMart Group - $25,000',
        clientCompanyName: 'Delta LLC',
        mcaCompanyName: 'MoneyMart Group',
        typeOfContract: 'Term Loan',
        originalRtr: '$25,000',
        loanDate: '2024-04-05',
        paymentFrequency: 'Monthly',
        paymentAmount: '$2,500',
        actualPayments: '$2,000',
        actualPaymentNote: 'Partial payment received',
        specifiedPercentage: '10%',
        actualPaymentDue: '$2,500',
        overUnderPayment: '-$500',
        fbd: 'Yes',
        currentRtrBalance: '$23,000',
        principalBalance: '$23,000',
        demandBalance: '$25,000',
        paymentStatus: 'Partially Paid',
        lienStatus: 'Active',
        settlementPriority: 'Low',
        notes: 'Late payment history.',
    },
    {
        slug: "5",
        clientMcaLoanName: 'AdvanceFunds Inc. - $60,000',
        clientCompanyName: 'Epsilon Co',
        mcaCompanyName: 'AdvanceFunds Inc.',
        typeOfContract: 'Revolving Credit',
        originalRtr: '$60,000',
        loanDate: '2024-05-01',
        paymentFrequency: 'Quarterly',
        paymentAmount: '$15,000',
        actualPayments: '$15,000',
        actualPaymentNote: 'On-time payment',
        specifiedPercentage: '25%',
        actualPaymentDue: '$15,000',
        overUnderPayment: '$0',
        fbd: 'No',
        currentRtrBalance: '$45,000',
        principalBalance: '$45,000',
        demandBalance: '$60,000',
        paymentStatus: 'Paid',
        lienStatus: 'Cleared',
        settlementPriority: 'High',
        notes: 'No issues reported.',
    },
];
