export const onBoardingData = [
    {
        slug: '1',
        clientCompanyName: 'ABC Corp',
        onboardingStartDate: '2023-05-10',
        onboardingStatus: 'Progress',
        notes: 'Client is undergoing onboarding.',
        signedGraAgreements: 'Completed',
        settlementNLC: 'Pending',
        settlementPOA: 'In Progress',
        mcaAgreements: 'Completed',
        bankStatements: 'Pending',
        copyOfDriversLicense: 'Completed',
        creditorInfo: 'In Progress',
        adInfo: 'Pending',
        deadline: '2023-09-01',
        additionalNotes: 'Awaiting documents.',
        merchantProcessingStatus: 'Pending',
        merchantProcessingPriority: 'High',
        merchantProcessingDeadline: '2023-09-15',
        merchantProcessingNotes: 'Urgent processing required.',
        paymentPlatformsStatus: 'In Progress',
        paymentPlatformsPriority: 'Medium',
        paymentPlatformsDeadline: '2023-09-20',
        paymentPlatformsNotes: 'Platform integration ongoing.',
        orderingPlatformsStatus: 'Pending',
        orderingPlatformsPriority: 'Low',
        orderingPlatformsDeadline: '2023-09-25',
        orderingPlatformsNotes: 'Awaiting client response.',
        insurancePaymentsStatus: 'Completed',
        insurancePaymentsPriority: 'High',
        insurancePaymentsDeadline: '2023-08-15',
        insurancePaymentsNotes: 'Payments processed successfully.',
        factoringStatus: 'Pending',
        factoringPriority: 'Medium',
        factoringDeadline: '2023-10-01',
        factoringNotes: 'Pending approval from the team.',
        checksCashStatus: 'In Progress',
        checksCashPriority: 'High',
        checksCashDeadline: '2023-09-05',
        checksCashNotes: 'Manual checks ongoing.',
        licenseTransferStatus: 'Completed',
        licenseTransferPriority: 'Low',
        licenseTransferDeadline: '2023-08-20',
        licenseTransferNotes: 'License transferred successfully.',
        generalLiabilityInsuranceTransferStatus: 'In Progress',
        generalLiabilityInsuranceTransferPriority: 'Medium',
        generalLiabilityInsuranceTransferDeadline: '2023-09-10',
        generalLiabilityInsuranceTransferNotes: 'Processing in the final stages.',
    },
    {
        slug: '2',
        clientCompanyName: 'XYZ Ltd',
        onboardingStartDate: '2023-06-01',
        onboardingStatus: 'Pending',
        notes: 'Client requested additional time.',
        signedGraAgreements: 'Pending',
        settlementNLC: 'In Progress',
        settlementPOA: 'Pending',
        mcaAgreements: 'Completed',
        bankStatements: 'Completed',
        copyOfDriversLicense: 'Pending',
        creditorInfo: 'In Progress',
        adInfo: 'Completed',
        deadline: '2023-09-10',
        additionalNotes: 'Follow up with the legal team.',
        merchantProcessingStatus: 'Completed',
        merchantProcessingPriority: 'Medium',
        merchantProcessingDeadline: '2023-09-18',
        merchantProcessingNotes: 'Processing completed without issues.',
        paymentPlatformsStatus: 'Pending',
        paymentPlatformsPriority: 'High',
        paymentPlatformsDeadline: '2023-09-25',
        paymentPlatformsNotes: 'Critical platform integration.',
        orderingPlatformsStatus: 'In Progress',
        orderingPlatformsPriority: 'Medium',
        orderingPlatformsDeadline: '2023-10-05',
        orderingPlatformsNotes: 'Ongoing platform testing.',
        insurancePaymentsStatus: 'In Progress',
        insurancePaymentsPriority: 'High',
        insurancePaymentsDeadline: '2023-09-22',
        insurancePaymentsNotes: 'Awaiting confirmation.',
        factoringStatus: 'Completed',
        factoringPriority: 'Medium',
        factoringDeadline: '2023-10-01',
        factoringNotes: 'Factoring completed successfully.',
        checksCashStatus: 'Pending',
        checksCashPriority: 'Low',
        checksCashDeadline: '2023-09-15',
        checksCashNotes: 'Pending additional checks.',
        licenseTransferStatus: 'In Progress',
        licenseTransferPriority: 'High',
        licenseTransferDeadline: '2023-09-30',
        licenseTransferNotes: 'Transfer in progress.',
        generalLiabilityInsuranceTransferStatus: 'Pending',
        generalLiabilityInsuranceTransferPriority: 'Medium',
        generalLiabilityInsuranceTransferDeadline: '2023-09-20',
        generalLiabilityInsuranceTransferNotes: 'Waiting for final documents.',
    },
    {
        slug: '3',
        clientCompanyName: 'LMN Inc',
        onboardingStartDate: '2023-07-15',
        onboardingStatus: 'Completed',
        notes: 'Client successfully onboarded.',
        signedGraAgreements: 'Completed',
        settlementNLC: 'Completed',
        settlementPOA: 'Completed',
        mcaAgreements: 'Completed',
        bankStatements: 'Completed',
        copyOfDriversLicense: 'Completed',
        creditorInfo: 'Completed',
        adInfo: 'Completed',
        deadline: '2023-09-05',
        additionalNotes: 'No further action required.',
        merchantProcessingStatus: 'Completed',
        merchantProcessingPriority: 'Low',
        merchantProcessingDeadline: '2023-09-15',
        merchantProcessingNotes: 'All tasks completed.',
        paymentPlatformsStatus: 'Completed',
        paymentPlatformsPriority: 'Low',
        paymentPlatformsDeadline: '2023-09-20',
        paymentPlatformsNotes: 'No issues encountered.',
        orderingPlatformsStatus: 'Completed',
        orderingPlatformsPriority: 'Low',
        orderingPlatformsDeadline: '2023-09-25',
        orderingPlatformsNotes: 'Platforms fully operational.',
        insurancePaymentsStatus: 'Completed',
        insurancePaymentsPriority: 'Medium',
        insurancePaymentsDeadline: '2023-08-30',
        insurancePaymentsNotes: 'Payments processed on time.',
        factoringStatus: 'Completed',
        factoringPriority: 'High',
        factoringDeadline: '2023-10-01',
        factoringNotes: 'Factoring closed successfully.',
        checksCashStatus: 'Completed',
        checksCashPriority: 'Medium',
        checksCashDeadline: '2023-09-05',
        checksCashNotes: 'All checks and cash reconciled.',
        licenseTransferStatus: 'Completed',
        licenseTransferPriority: 'Low',
        licenseTransferDeadline: '2023-08-10',
        licenseTransferNotes: 'License transferred without issues.',
        generalLiabilityInsuranceTransferStatus: 'Completed',
        generalLiabilityInsuranceTransferPriority: 'High',
        generalLiabilityInsuranceTransferDeadline: '2023-09-01',
        generalLiabilityInsuranceTransferNotes: 'Insurance transfer successful.',
    },
];
