// Dummy data
export const revenueSourceData = [
    {slug:"1",
        revenueSourceCompanyType: 'Type 1',
        revenueSourceCompanyName: 'Company A',
        businessWebsite: 'www.companyA.com',
        businessAddress: '123 Street, City',
        name: 'John Doe',
        phone: '123-456-7890',
        email: 'john@example.com',
        notes: 'Some notes here',
    },
    {slug:"2",
        revenueSourceCompanyType: 'Type 2',
        revenueSourceCompanyName: 'Company B',
        businessWebsite: 'www.companyB.com',
        businessAddress: '456 Avenue, City',
        name: 'Jane Smith',
        phone: '987-654-3210',
        email: 'jane@example.com',
        notes: 'Additional notes',
    },
    {slug:"3",
        revenueSourceCompanyType: 'Type 3',
        revenueSourceCompanyName: 'Company C',
        businessWebsite: 'www.companyC.com',
        businessAddress: '789 Boulevard, City',
        name: 'Alice Johnson',
        phone: '555-555-5555',
        email: 'alice@example.com',
        notes: 'Further notes',
    },
];
