export const clientMcaSettlementData = [
    {
        slug: '1',
        clientMcaLoanId: 'LC12346',
        thirdPartyCompanyName: 'QuickFunds Ltd.',
        clientCompanyName: 'Company 3',
        mcaCompanyName: 'MCA COM 3',
        balanceRTR: '$3000',
        status: 'Pending',
        clientName: 'Michael Brown',
        notes: 'Awaiting approval from management.',
        date: '2024-08-01',
        mcaCoOr3rdParty: '3rd Party',
        contactName: 'Alice Johnson',
        graRepresentative: 'Michael Brown',
        type: 'Counter',
        amount: '$25,000',
        responseDate: '2024-07-28',
        percentage: '50%',
        comments: 'Counter-offer submitted, awaiting response.',
        settlementdate: '',
        settlementmcaCoOr3rdParty: '',
        settlementcontactName: '',
        settlementgraRepresentative: '',
        settlementAmount: '',
        settlementTerms: '',
        settlementPercentage: '',
    },
    {
        slug: '2',
        clientMcaLoanId: 'LC12346',
        clientCompanyName: 'Company 3',
        mcaCompanyName: 'MCA COM 3',
        balanceRTR: '$3000',
        thirdPartyCompanyName: 'QuickFunds Ltd.',
        status: 'Pending',
        clientName: 'Michael Brown',

        notes: 'Awaiting approval from management.',
        date: '2024-08-01',
        mcaCoOr3rdParty: '3rd Party',
        contactName: 'Alice Johnson',
        graRepresentative: 'Michael Brown',
        type: 'Counter',
        amount: '$25,000',
        responseDate: '2024-07-28',
        percentage: '50%',
        comments: 'Counter-offer submitted, awaiting response.',
        settlementdate: '',
        settlementmcaCoOr3rdParty: '',
        settlementcontactName: '',
        settlementgraRepresentative: '',
        settlementAmount: '',
        settlementTerms: '',
        settlementPercentage: '',
    },
    {
        slug: '3',
        clientMcaLoanId: 'LC12346',
        clientCompanyName: 'Company 3',
        mcaCompanyName: 'MCA COM 3',
        balanceRTR: '$3000',
        thirdPartyCompanyName: 'QuickFunds Ltd.',
        status: 'Pending',
        clientName: 'Michael Brown',

        notes: 'Awaiting approval from management.',
        date: '2024-08-01',
        mcaCoOr3rdParty: '3rd Party',
        contactName: 'Alice Johnson',
        graRepresentative: 'Michael Brown',
        type: 'Counter',
        amount: '$25,000',
        responseDate: '2024-07-28',
        percentage: '50%',
        comments: 'Counter-offer submitted, awaiting response.',
        settlementdate: '',
        settlementmcaCoOr3rdParty: '',
        settlementcontactName: '',
        settlementgraRepresentative: '',
        settlementAmount: '',
        settlementTerms: '',
        settlementPercentage: '',
    },
];
